services:
  - type: web
    name: virtual-cafe
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT wsgi:app"
    envVars:
      - key: FLASK_CONFIG
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: virtualcafe
          property: connectionString

databases:
  - name: virtualcafe
    databaseName: virtualcafe
    user: virtualcafe